<?php

namespace Database\Seeders;

use App\Models\Student;
use Illuminate\Database\Seeder;

class student_seeder extends Seeder
{
    public function run(): void
    {

        $data = [
            [
                "user_id" => 9,
                "teacher_id" => null,
                "name" => "Vanessa Wibisono",
                'parentname' => null,
                'nickname' => "Vanessa",
                'birthdate' => null,
                'birthplace' => "Surabaya",
                'schoolname' => "Little Sun",
                'address' => null,
                'phone' => null,
                'grade' => "9",
                'age' => null,
                'religion' => "Budha",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "user_id" => 10,
                "teacher_id" => null,
                "name" => " Charlotte Olivia Tjandra",
                'parentname' => null,
                'nickname' => "Lottie",
                'birthdate' => null,
                'birthplace' => "Surabaya",
                'schoolname' => "Petra 5",
                'address' => null,
                'phone' => null,
                'grade' => "TK A",
                'age' => null,
                'religion' => "Kristen",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "user_id" => 11,
                "teacher_id" => null,
                "name" => "Calev Tanuwijoyo",
                'parentname' => null,
                'nickname' => "Calev",
                'birthdate' => null,
                'birthplace' => "Surabaya",
                'schoolname' => "Ellyon",
                'address' => null,
                'phone' => null,
                'grade' => "TK B",
                'age' => null,
                'religion' => "Kristen",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "user_id" => 12,
                "teacher_id" => null,
                "name" => "George",
                'parentname' => null,
                'nickname' => " George",
                'birthdate' => null,
                'birthplace' => "Surabaya",
                'schoolname' => "Sampoerna Academy",
                'address' => null,
                'phone' => null,
                'grade' => "Preschool",
                'age' => null,
                'religion' => "Kristen",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "user_id" => 13,
                "teacher_id" => null,
                "name" => "Kanaya",
                'parentname' => null,
                'nickname' => "Kanaya",
                'birthdate' => null,
                'birthplace' => "Surabaya",
                'schoolname' => "Benih Kasih",
                'address' => null,
                'phone' => null,
                'grade' => "TK B",
                'age' => null,
                'religion' => "Kristen",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "user_id" => 14,
                "teacher_id" => null,
                "name" => "Matthew G",
                'parentname' => null,
                'nickname' => " Matthew",
                'birthdate' => null,
                'birthplace' => "Surabaya",
                'schoolname' => "Bunga bangsa",
                'address' => null,
                'phone' => null,
                'grade' => 8,
                'age' => null,
                'religion' => "Kristen",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "user_id" => 15,
                "teacher_id" => null,
                "name" => "Hansel Orlando Tjoatmaja",
                'parentname' => null,
                'nickname' => " Hansel",
                'birthdate' => null,
                'birthplace' => "Surabaya",
                'schoolname' => "Sd Theresia 1",
                'address' => null,
                'phone' => null,
                'grade' => 2,
                'age' => null,
                'religion' => "Kristen",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "user_id" => 16,
                "teacher_id" => null,
                "name" => "Angela Faye Santoso",
                'parentname' => null,
                'nickname' => "Angela",
                'birthdate' => null,
                'birthplace' => "Surabaya",
                'schoolname' => "Sampoerna Academy",
                'address' => null,
                'phone' => null,
                'grade' => "Preschool",
                'age' => null,
                'religion' => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "user_id" => 17,
                "teacher_id" => null,
                "name" => "Adinda Etikasari Putri",
                'parentname' => null,
                'nickname' => "Dinda",
                'birthdate' => null,
                'birthplace' => "Surabaya",
                'schoolname' => "SDN Semolowaru",
                'address' => null,
                'phone' => null,
                'grade' => 2,
                'age' => null,
                'religion' => "Islam",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "user_id" => 18,
                "teacher_id" => null,
                "name" => "Jonathan Bima Bayu Saputra",
                'parentname' => null,
                'nickname' => "Jojo",
                'birthdate' => null,
                'birthplace' => "Surabaya",
                'schoolname' => "belum sekolah",
                'address' => null,
                'phone' => null,
                'grade' => "belum sekolah",
                'age' => null,
                'religion' => "Budha",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "user_id" => 19,
                "teacher_id" => null,
                "name" => "Muhammad Alvin hari pratista",
                'parentname' => null,
                'nickname' => "Alvin",
                'birthdate' => null,
                'birthplace' => "Surabaya",
                'schoolname' => "SDN kertajaya",
                'address' => null,
                'phone' => null,
                'grade' => 1,
                'age' => null,
                'religion' => "Islam",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "user_id" => 20,
                "teacher_id" => null,
                "name" => "Rafael Hieronimus Yoewono",
                'parentname' => null,
                'nickname' => "Rafael",
                'birthdate' => null,
                'birthplace' => "Surabaya",
                'schoolname' => "Gloria",
                'address' => null,
                'phone' => null,
                'grade' => "PG B",
                'age' => null,
                'religion' => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "user_id" => 21,
                "teacher_id" => null,
                "name" => "Queenara Azzalea Elshanum Nurangga",
                'parentname' => null,
                'nickname' => "Alea",
                'birthdate' => null,
                'birthplace' => "Gresik",
                'schoolname' => "Belum Sekolah",
                'address' => null,
                'phone' => null,
                'grade' => "Preschool",
                'age' => null,
                'religion' => "Islam",
                "created_at" => now(),
                "updated_at" => now(),
            ],
        ];

        Student::insert($data);
    }
}
